### ISSUE TITLE
Make GET request to return user orgs with an array of boardId's or names

### ISSUE THREAD

**Issue by tylerminnis** [Sync-Space-49/syncspace-server#54]
## Problem

Currently, mobile has to get user orgs, get boardIds for all user orgs, then get board by ID for each board. The issue is that it's a lot of requests back and forth over the internet which is slow and running into 'too many requests' most likely because I'm sending like 20 requests 2 seconds

also this is the current issue whenever a user has more than one org, even though the same requests work in postman: 
`Failed to get user permissions: failed to get user roles: failed to get permissions: {"statusCode":429,"error":"Too Many Requests","message":"Global limit has been reached","errorCode":"too_many_requests"}`

## Potential Solution

have a method in the backend that gives the same response as Get User Organizations but with an array of either all the board names or board ids for each org.

ex response of what i was thinking: 
```{ 
"id": "id", 
"owner_id": "auth0:id",
"name": "SyncSpace",
"description": "The project management tool that's so easy, it's out of this world!",
"boards": [
"Mobile",
"Web",
"Backend",
"Marketing"
]
} 
```

if there are better ways that you guys can think about this, feel free to implement it in another way.

**Comment by DylanHalstead** [comment]
In the current version of `GetViewableBoardsInOrg` there is a lot of pinging to auth0 to check what permissions are on a user. Even if the board is not private we always make this check:
![image](https://github.com/Sync-Space-49/syncspace-server/assets/70990184/8f689c89-54e0-492d-bc47-f2095763e11f)

I've rewritten this function while working on #47 so that we only ping auth0 when we need to:
![image](https://github.com/Sync-Space-49/syncspace-server/assets/70990184/cfa6ec95-5ff1-443e-bfea-b37ce260f814)

Hopefully, this helps take strain away and keeps us from hitting the auth0 request limit. Being I'm already making routes with `/details`, if this doesn't fix the issue we can write a function like above. May need to rewrite some functions in general. I think there is a way to check a user's permissions on the token they send? Will help alot with our auth0 pings but that gets into messing with auth0 RBAC and auth0 is already being held together by a string...
